name: app_shoes_ec
description: "VMO"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  dotted_line: ^3.2.2
  dotted_border: ^2.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3
  intl: ^0.18.1
  photo_view: ^0.15.0
  iconly: ^1.0.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  go_router: ^14.2.0
  shared_preferences: ^2.2.3

  user_repository:
    path: packages/user_repository

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.1.0+1

flutter_gen:
  output: lib/gen/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/common/appicon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/af107/
    - assets/images/background/
    - assets/icons/cart/
    - assets/icons/common/
    - assets/icons/direction/
    - assets/icons/flags/
    - assets/icons/mode/
    - assets/icons/nav/
    - assets/icons/shoes/

flutter_intl:
  enabled: true
  
